### ISSUE TITLE
Unable to load/save config in NixOS

### ISSUE THREAD

**Issue by geoffreybennett** [geoffreybennett/alsa-scarlett-gui#101]
The fix in issue #65 broke NixOS which keeps `alsactl` in `/run/current-system/sw/bin`. Probably should search `$PATH` _and_ `/usr/sbin`.

**Comment by yoyoyonono** [comment]
Is there any workaround other than running whatever `alsactl store`/`restore` command it tries to run yourself?

**Comment by geoffreybennett** [comment]
Hi @yoyoyonono,

1) Is alsactl in your path? (if not, (2) won't help)

2) Please try reverting that fix and let me know if that helps (`git revert 1839c186`).

Thanks,
Geoffrey.

**Comment by geoffreybennett** [comment]
I pushed a fix to the master branch. Please check it out and reopen this issue if that doesn't fix it for you.

**Comment by yoyoyonono** [comment]
I can't actually get it to work properly because it keeps complaining about not having gsettings schemas or whatever. That's likely my fault though. 

It did work once, though, but it gave me the same error message that I'm getting in the release version. Again, that's probably my fault.

I'll probably just wait for it to trickle down through nixpkg and try it then because if the fix worked it'll probably work there.
