### ISSUE TITLE
Feature Request: Add lock function for physical DIM button

### ISSUE THREAD

**Issue by renne** [geoffreybennett/alsa-scarlett-gui#132]
Hi, phantastic project! 🥇 

We regularly connect unbalanced HiFi devices with 1/4" TS-to-Cinch/RCA adapters to the outputs of the 18i20 and use the DIM function to protect the input stages of the HiFi devices.

If someone accidentially or a (man)child presses the physical DIM button the deactivation of the DIM function can blow the input stages of the unbalanced HiFi devices with 15.5 dBu.

It would be great to have a configurable locking mechanism for the DIM function which ignores the physical DIM button. :-)

**Comment by geoffreybennett** [comment]
Hi @renne,

There's no such functionality as such (that I know of) in the Scarlett firmware, so that would be a request that you'd need to make to Focusrite.

Instead: how about applying a volume reduction using the mixer functionality of the Scarlett? That can't be disabled from the front panel.

E.g. from the routing window of the Scarlett, if you've got PCM Outputs connected to Hardware Outputs, then instead do PCM Outputs → Mixer Inputs and Mixer Outputs → Hardware Outputs. Then in the mixer window set all the knobs to -∞dB except for these which you set to the desired value (e.g. -12dB):
- Mix A Analogue 1
- Mix B Analogue 2
- etc., for however many hardware outputs you are using

Another idea I had, if you don't need to use the front panel volume knob: set the HW/SW controls to "SW". That makes the HW (front panel) volume controls do nothing, and you can fix the volume using the Analogue Output volume controls on the main screen.

Regards,
Geoffrey.

**Comment by renne** [comment]
@geoffreybennett 
Focusrite support says it is not possible to limit the hardware knob access.
So, thank you very much for the suggestion!
🥇 for your professional support! 😁

**Comment by geoffreybennett** [comment]
You're welcome! Glad I could help!
