### ISSUE TITLE
¿isn't better to create a kernel module instead of a complete kernel?

### ISSUE THREAD

**Issue by juanpc2018** [geoffreybennett/alsa-scarlett-gui#31]
for example:
rapiddisk,
https://github.com/pkoutoupis/rapiddisk

creates a kernel module, 
and loads the module,
everytime there is a Kernel change,
rapiddisk needs to be uninstalled, build again from source, and re-installed to the new kernel.
similar happens to rEFInd.
Marvell AQtion PCIe SFP+ Network cards, 
etc...
 
external module gives fredom to solve issues faster,
instead of waiting for a New Kernel.
or compile a complete new kernel.

this method makes No sense to me.

Drivers embeded into the Kernel looks like OSX,
very weird.

example:
AMD 6000xt requires OSX BigSur 11.x minimum.
AMD 5000xt requires OSX Catalina 10.15.x minimum.
AMD Radeon VII requires OSX Mojave 10.14.x minimum.
AMD HD7950 works since OSX 10.6.8
But..PCIe,  does Not work using eGPU,
Thunderbotl2 eGPU works up-to OSX 10.13.3 "10.13.4 Beta4", then was Deleted from Kernel.,
Thunderbolt3 eGPU worls since OSX HighSierra 10.13.4
Only Rx 400,  500, maybe R9 290 can work in eGPU with TB2 up-to OSX 10.13.3

if you purchased a software or hardware that only runs upto OSX HighSierra 10.13.
you cannot upgrade your video card,
if you do, you need to change your complete machine, osx, etc...
Black or White, No medium ground for update / upgrade.

That method is used by the Fruit company to Break backward compatibility.
Old intel Macs cannot run Newer OSX,
Newer OSX cannot be installed in Older Macs,
Newer Macs cannot run older OSX.
people are forced to buy a complete New system computer, scanner, etc...
or stay with older until it breaks, and continue to buy older to continue using older drivers, older osx, etc...

OSX designed for intel x86_64
since OSX 10.5.8 to OSX 10.15.7
but different OSX versions are incompatible with most intel Macs.
Only certain years are compatible with certain HW.
Only certain OSX are compatible with certain HW.

OSX had a PowerPC CPU emulator in OSX SnowLeopard 10.6.
but was Deleted in OSX Lion 10.7
and most intel macs from 2012 and newer cannot install OSX SnowLeopard 10.6 desgined for intel,
it becomes an Unjust Oppressive Power.. "Tyranny"

P.D.
default alsa kernel module can be put in blacklist.conf
when installing a newer module.
or
modprobe -r

**Comment by geoffreybennett** [comment]
Absolutely not. It is much better to have the driver as part of the Linux kernel.

Since 5.4 (Gen 2) and 5.14 (Gen 3), end-users don't need to build anything. If it was a module, then as you say, it's a lot more work for everyone trying to use the driver: "everytime there is a Kernel change, rapiddisk needs to be uninstalled, build again from source, and re-installed to the new kernel".

Imagine doing this for every driver. On my laptop right now:

```
$ lsmod | wc -l
174
```

Rebuild 174 modules every time there's a kernel update? Insane!

This isn't like the "Fruit company". And this is the wrong place for discussion; all the code in this repo is user-space, not kernel-space.

If you really want to try doing this then look at HinTak's work here: https://github.com/Focusrite-Scarlett-on-Linux/sound-usb-kernel-module
