### ISSUE TITLE
Add support for Clarett devices

### ISSUE THREAD

**Issue by geoffreybennett** [geoffreybennett/alsa-scarlett-gui#34]
Kernel patch with Clarett+ Pre8 (and maybe Clarett Pre8 USB) support is here: https://github.com/geoffreybennett/scarlett-gen2/commits/scarlett-gen3

Tiny patch to add support to alsa-scarlett-gui is in the dev branch.

If you can, please test and advise.

**Comment by newspacer** [comment]
Hi, I just wanted to check the status of this?  Looks to me like the changes required for Clarett+ 8Pre support are already merged to Master, so was just curious if there's any reason this issue is still open?  (Also, the project readme says Clarett+ 8Pre support is coming in kernel 6.1; the mainline kernel is already on 6.2+, so I guess that can be updated ;-) )

**Comment by 71GA** [comment]
I am also confused about this. Is Clarett+ 8pre supported in the kernel 6.1?

**Comment by geoffreybennett** [comment]
I had left this open because the title was "Add support for Clarett devices" and only Clarett+ 8Pre support had been done, until recently. Time to close, because it's done now. Thanks newspacer & 71GA.
