### ISSUE TITLE
Enabling the use of the monitor control knob via the gui

### ISSUE THREAD

**Issue by adam248** [geoffreybennett/alsa-scarlett-gui#51]
I am not sure if this is a missing feature or I can't see it.

I am rocking: 
```
Focusrite Scarlett 4i4 3rd Gen.
OS: NixOS 23.05.1998.f64b9738da8 (Stoat) x86_64 
Kernel: 6.4.3
```

I have searched though multiple docs and found this in the official guide:
![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/85082674/27489231-65a6-4a99-b9f1-604dc1256a73)

However, I cannot find it in `alsa-scarlett-gui` nor in `alsamixer`.

I read this post: https://linuxmusicians.com/viewtopic.php?p=120523&hilit=Monitor+Controls#p120523

Question: Is this driver the only currently known way to get the monitor knob working on Linux?
Question: Can this driver work with Linux kernel 6+?
Question: If this driver is installed, will the option be available in `alsa-scarlett-gui`?
Question: What driver is being used by default in Linux for the Scarlett 4i4? Or how can I see what driver I am currently using?

I know I am asking a lot so if some of the questions are out-of-scope here I understand.

Any other clarification regarding this issue would be much appreciated.
Thank you

**Comment by geoffreybennett** [comment]
Hi Adam, the feature does exist in the GUI, but as per your screenshot above is only applicable to the 18i8 and 18i20. The 4i4 has only the hardware controls on the front panel. Software control of the volume is not possible.

On 18i8 and 18i20 interfaces it appears like this:
![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/1866657/f8d40cf9-5af1-455f-a055-e92e1f4ab65b)

Click the SW/HW buttons to toggle the selection per-channel (Focusrite Control is not as flexible, only supporting fixed sets of channels).

_I read this post: https://linuxmusicians.com/viewtopic.php?p=120523&hilit=Monitor+Controls#p120523_
That's a very old post. Read the README.md of this project for more up-to-date information.

_Question: Is this driver the only currently known way to get the monitor knob working on Linux?_
No. The monitor knob on the 4i4 is hardware only and there's nothing you need to do to get it to work (of course, there might be other things misunderstood, misconfigured, or broken!).

_Question: Can this driver work with Linux kernel 6+?_
The driver is already present in the kernel for Gen3 devices since 5.14.

_Question: If this driver is installed, will the option be available in alsa-scarlett-gui?_
Not applicable.

_Question: What driver is being used by default in Linux for the Scarlett 4i4? Or how can I see what driver I am currently using?_
Run `dmesg | grep Focusrite` after plugging in your interface to see if the driver is enabled or disabled.
