### ISSUE TITLE
Replace Makefile with meson?

### ISSUE THREAD

**Issue by geoffreybennett** [geoffreybennett/alsa-scarlett-gui#62]
> Hi, AFAIK meson is the way for most of the gtk/gnome apps. I think its also simple and easy to use and a well stabilized project. https://mesonbuild.com/

_Originally posted by @saxa in https://github.com/geoffreybennett/alsa-scarlett-gui/issues/50#issuecomment-1711470243_

**Comment by Sonophoto** [comment]
This is the ol "you aren't using my tool" complaint. I would ignore it and focus on more important things. The make file for this project is simple and works fine.

**Comment by geoffreybennett** [comment]
Thanks for your comment @Sonophoto. I do feel like the Makefile is a bit horrendous, but learning another build tool is currently at the bottom of my to-do list so I appreciate your vote to ignore. Onward with the Gen 4 support! :)

As I wrote in the referenced issue: "I have no idea what the standard practice is here; developing desktop apps is not my area of expertise. If anyone wants to make this better, contributions are welcome."

**Comment by 71GA** [comment]
@geoffreybennett Please do not use `meson` or anything else than `make`. Only people who don't understand it will complain, but people who know it realize that it is basically the simplest and best build system.

**Comment by geoffreybennett** [comment]
Sounds good to me, thanks for the advice.

**Comment by saxa** [comment]
Hi I know this issue is closed, but I step up and made some steps in implementing meson to build this project. 
Right now I can build the project but its not yet installable and some small things still need to be fixed. Its a work in progress. 
If somebody is interested in this can find my work over here:
https://github.com/saxa/alsa-scarlett-gui

I noticed that some things in the Makefiles in the original project should be handled more elegantly , like for example the VERSION variable, which gets substituted in the about.c file at compile time. I implemented it the same way in meson, but surely a config.h.in file would be more elegant as it would also expand more options for the future and be buildable easily on different platforms. Anyway, thats not an issue at all.

Comments welcome.

**Comment by saxa** [comment]
just as an update, I have also implement the resources file compilation. I tested the application without installing it and since I don't have the my scarlett connected I used the .state file from the data directry.
So far the interface seems working, but would be nice if somebody who has the sound card connected could test the application and confirm if it works ok.
If so I start working on the installing it and and packaging it to.
