### ISSUE TITLE
Question about standalone mode

### ISSUE THREAD

**Issue by 4oo4** [geoffreybennett/alsa-scarlett-gui#63]
I'm having trouble being able to use standalone mode with an 18i8, I did see this super helpful comment you posted about disabling `alsactl`, (if I understand right that means it saves the settings to the NVRAM on the Scarlett instead of having the settings applied after boot?), however I still am not getting audio routing when I try to use it in standalone mode and my computer is off.

https://github.com/geoffreybennett/alsa-scarlett-gui/issues/54#issuecomment-1706954773

Do I need to be doing anything else like making sure that the USB cable is disconnected when the computer is off, or using a mixer input/output instead of going from a Hardware Input --> PCM Input --> PCM Output --> Hardware Output? Currently I'm not using any onboard mixing, but rather just trying to do some simple routing from a couple analog inputs to hardware outputs.

![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/15698835/18aaf801-90cb-468a-a927-a7f5a4abd78c)

Thanks!

**Comment by geoffreybennett** [comment]
Hi @4oo4!

To make standalone mode work you need to set up the routing beforehand so that Hardware Inputs go to Hardware Outputs, either directly or via the Mixer. With the computer off, nothing is going to come from the PCM Outputs, therefore nothing will go to the Hardware Outputs.

Regarding disabling alsactl, that won't be an issue in this particular case (at least, not until you turn the computer back on!). The configuration is always saved into Scarlett's NVRAM moments after you make any change. The problem with alsactl is when it saved an old config (when you shut down your computer with the interface connected) and then it overwrites what was in the Scarlett NVRAM with an old config every time you boot up your computer or plug your interface in.

Regards,
Geoffrey.

**Comment by 4oo4** [comment]
Great, I suspected that was the case, thanks for confirming. Will give that a try.

Thanks again!
