### ISSUE TITLE
Clarett+ 8pre inconsistencies in documentation

### ISSUE THREAD

**Issue by 71GA** [geoffreybennett/alsa-scarlett-gui#76]
Documentation for `alsa-scarlett-gui` states ([link](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/README.md?plain=1#L22)) that _"Clarett+ 8pre"_  is already supported in _"Linux kernel v6.1"_ while documentation for `scarlet-gen2` driver ([link](https://github.com/geoffreybennett/scarlett-gen2/releases)) states that it is supported in the latest driver version `v6.5.11c1` which is included in _"Linux kernel v6.7"_.

From the later link it seems that support for _"Clarett+ 4Pre"_ and not _"Clarett+ 8pre"_ was added a bit earlier with the version `v6.5.3c1` of the `scarlet-gen2` driver.

So which one is it? It would be good to unite the documentation.

**Comment by geoffreybennett** [comment]
Regarding mainstream kernel versions, the README.md is correct. Clarett+ 8Pre since 6.1, and the rest of the Clarett USB and Clarett+ devices since 6.7.

The info at the scarlett-gen2 repo is is also correct, but you need to note that v6.5.3c1 and v6.5.11c1 are tags that are only relevant to my kernel repo. That repo is where I share the driver for people to test before they can get the driver through their distribution or a mainstream kernel. What I added in v6.5.3c1 (Clarett+ 4Pre) and v6.5.11c1 (the rest of them) made it into Linux 6.7.

I don't think it's useful to refer to those v6.5.xcy versions in the alsa-scarlett-gui documentation as they're not actual kernel versions, and they soon become irrelevant.

I updated the notes at [link](https://github.com/geoffreybennett/scarlett-gen2/releases) to clarify that Clarett+ 8Pre support is not new.

I hope this helps?

**Comment by 71GA** [comment]
This is now spot on!
