### ISSUE TITLE
Bitrate options

### ISSUE THREAD

**Issue by alphonsom** [geoffreybennett/alsa-scarlett-gui#81]
This may not qualify as an issue, because it may not be part of the intentions of the design. But there seems to be no option for changing the operating bitrate between 96KHz, 88KHz, 48KHz and 44KHz as in Focusrite's Windows/MacOS frontend.

**Comment by geoffreybennett** [comment]
Hi @alphonsom,

The primary function of the Scarlett2 mixer driver (for which alsa-scarlett-gui is a front-end) is internal audio routing and mixing within the device, as well as managing settings on the device itself. It's important to note that the Scarlett2 driver doesn't handle the audio input/output to and from the device. Instead, this task is managed by the ALSA generic USB soundcard driver.

In Linux, the sample rate is chosen by the application that opens the soundcard using the ALSA API. That could be PulseAudio or JACK or PipeWire, or the end-user application if it's using the ALSA device directly (e.g. Ardour or Audacity).

Therefore, I'm trying to keep the sample rate setting outside the scope of this project. The best I could do would be to monitor `/proc/asound/*/stream0` to see if some application has the soundcard open and read what sample rate it has requested. Otherwise this project would turn into a frontend for configuring PulseAudio/JACK/PipeWire/Ardour/Audacity.

Regards,
Geoffrey.

**Comment by alphonsom** [comment]
Of course. I should have given it two minutes thought before posting.

**Comment by geoffreybennett** [comment]
All good. It's a frequently asked question. I should create an `FAQ.md`...
