### ISSUE TITLE
Gen 4 support ?

### ISSUE THREAD

**Issue by lyderic** [geoffreybennett/alsa-scarlett-gui#82]
I was about to buy a 2i2 Gen 4. However, it looks like the Gen 4 devices are not supported yet (please see screenshot I took immediately after compiling the most recent master's HEAD).

I understand Geoffrey is working on Gen 4 support, can you please confirm that it is safe to buy a Gen 4? I am happy to help testing ;-)

Many thanks,
L.

![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/5059957/52f2e147-d758-430e-9d84-b60d621278a0)

**Comment by geoffreybennett** [comment]
Hi @lyderic,

Definite recommend on the interface. It works fine in Linux already with the generic ALSA USB audio driver because it's USB Class Compliant, so don't wait for me!

It has lots of buttons on the front, so it's not like the Gen 3 4i4 and bigger models that only had software control of important functions.

That said, I am in the final stages of testing (and refactoring and fixing and repeat...) the Gen 4 support. When done, you'll have all the control over the interface from inside Linux:

![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/1866657/8899bedc-9bad-4ce2-b360-994d9e7ee9a0)

Regards,
Geoffrey.

**Comment by lyderic** [comment]
Excellent! Many thanks Geoffrey!
L.

**Comment by geoffreybennett** [comment]
First draft released!

Kernel driver: https://github.com/geoffreybennett/scarlett-gen2/releases/tag/v6.5.11-g4.1

Firmware update utility: https://github.com/geoffreybennett/scarlett2

Please email me if you'd like to assist testing.

**Comment by gwilherm** [comment]
Wow a firmware update utility ! :open_mouth:

**Comment by geoffreybennett** [comment]
Dup of #61.
